price_patterns:
  - '(?:\\$|€|£)\\s?([0-9]+[\\.,][0-9]{2})'
  - '([0-9]+[\\.,][0-9]{2})\\s?(USD|EUR|GBP)'
promotions:
  - '(\\d+)\\s*for\\s*(?:\\$|€|£)\\s*([0-9]+[\\.,][0-9]{2})'
  - 'save\\s*(?:\\$|€|£)\\s*([0-9]+[\\.,][0-9]{2})'
currency_symbols: ['$', '€', '£']
decimal_sep: '.'
